site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:11001", "s201:11002", "s301:11003", "s401:11004", "s501:11005", "s601:11006", "s701:11007", "s801:11008", "s901:11009", "s1001:11010", "s1101:11011"]
  client: # each line is a partition
    - ["c101", "c201", "c301", "c401", "c501", "c601", "c701", "c801", "c901", "c1001",
    "c1101", "c1201", "c1301", "c1401", "c1501"]

# process_name - host_addr map
process:
  s101: localhost
  s201: localhost
  s301: localhost
  s401: localhost
  s501: localhost
  s601: localhost
  s701: localhost
  s801: localhost
  s901: localhost
  s1001: localhost
  s1101: localhost
  c101: localhost
  c201: localhost
  c301: localhost
  c401: localhost
  c501: localhost
  c601: localhost
  c701: localhost
  c801: localhost
  c901: localhost
  c1001: localhost
  c1101: localhost
  c1201: localhost
  c1301: localhost
  c1401: localhost
  c1501: localhost
    
host:
  localhost: 127.0.0.1

