site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:11001", "s201:11002", "s301:11003", "s401:11004", "s501:11005"]
  client: # each line is a partition
    - ["c101"]

# process_name - host_addr map
process:
  s101: localhost
  s201: localhost
  s301: localhost
  s401: localhost
  s501: localhost
  c101: localhost
    
host:
  localhost: 127.0.0.1

