
site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:18000", "s201:18001"]
  client: # each line is a partition
    - ["c01"]

# site_name - process_name map
process:
  s101: localhost 
  s201: localhost 
  # s301: localhost 
  c01: localhost 
host:
  localhost: 127.0.0.1
  v1: 10.128.0.20 
  v2: 10.128.0.22 
  # v3: 10.128.0.23 
