
site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:12000", "s201:12001", "s301:12002"]
  client: # each line is a partition
    - ["c101", "c201", "c301"]

# site_name - process_name map
process:
  s101: localhost
  s201: localhost
  s301: localhost
  c101: localhost
  c201: localhost
  c301: localhost

host:
  localhost: 127.0.0.1
