
site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:9130", "s201:9131", "s301:9132", "s401:9133", "s501:9134"]
  client: # each line is a partition
    - ["c101", "c201", "c301"]

# site_name - process_name map
process:
  s101: localhost
  s201: localhost
  s301: localhost
  s401: localhost
  s501: localhost
  c101: localhost
  c201: localhost
  c301: localhost

# process_name - host_addr map
host:
  localhost: 127.0.0.1
  # h01: 127.0.0.1
  # h02: 127.0.0.1
  # h03: 127.0.0.1
  # h04: 127.0.0.1