
site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:8000", "s201:8001", "s301:8002"]
  client: # each line is a partition
    - ["c101", "c201", "c301"]
    - ["c102", "c202", "c302"]
    - ["c103", "c203", "c303"]
    - ["c104", "c204", "c304"]
    - ["c105", "c205", "c305"]
    - ["c106", "c206", "c306"]
